name: daily

on:
  workflow_dispatch:
  schedule:
    - cron: '24 23 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: >
          curl --location --fail --silent --show-error -o repo-cleaner.jar https://github.com/ByteLegend/tools/releases/download/v1.0.0/repo-cleaner.jar &&
          java
          -DgitHubToken=${{ secrets.GITHUB_TOKEN }}
          -DrepoFullName="$GITHUB_REPOSITORY"
          -jar repo-cleaner.jar
